### PR TITLE
DC: create web interface for changing IP address

### PR DESCRIPTION
**Pull request by dnutan**
NethServer/dev#5330

### CODE REVIEW

**Comment by DavidePrincipi** [comment]
Thank you @dnutan: the patch is perfect!

image

I'd prefer a separate dialog form, though. It would avoid confusion with the "Create a new domain" form (they are quite the same), and warn the admin about [possible problems with existing clients](https://wiki.samba.org/index.php/Changing_the_IP_Address_of_a_Samba_AD_DC).

The implementation could be similar to the "Uninstall" button. I think that removing the main "Submit" button here has the implicit message: "do not touch anything here!" :)

What do you think?

**Comment by dnutan** [comment]
I thought to have an "Unlock" button to activate the editable fields (and show/unlock the "Submit" button). 
At this time there's only one possible change (IP), but in the future could be the netbios name also. A dialog form will handle both fields at a time or set an action button and a dialog for each one?

Agree on the additional warning.

Would it make sense to force a configuration backup before saving the changes?

**Comment by DavidePrincipi** [comment]
> I thought to have an "Unlock" button to activate the editable fields (and show/unlock the "Submit" button).

It could work, however I'd avoid the introduction of new UI behavior patterns.

> At this time there's only one possible change (IP), but in the future could be the netbios name also.

Do you have any documentation about it?

> A dialog form will handle both fields at a time or set an action button and a dialog for each one?

I'd go with a dialog for each one. They seem different use cases.

> Would it make sense to force a configuration backup before saving the changes?

Not sure. Yes, it is useful, but it would be an entirely new thing: "the system configuration history, with rollback..." and every system change should be preceded by a configuration backup. Too much, by now.

**Comment by dnutan** [comment]
>I'd avoid the introduction of new UI behavior patterns.

Fair enough.

>Do you have any documentation about it?

No, I think to recall there was some user request, but I could we wrong.
I found this, but the change could be calling for problems, and Red Hat recommends not to change it:
* https://techjourney.net/rename-ad-domain-name-in-windows-server-2012/
* http://sdb.univention.de/content/6/313/en/how-can-the-netbios-domain-name-be-changed.html
* http://samba.2283325.n4.nabble.com/Rename-domain-during-classicupgrade-step-td4718604.html

>Changing the NetBIOS name in most cases requires to re-establish all existing trusts. Therefore, Red Hat recommends not to change the attribute.

**Comment by dnutan** [comment]
Please check for a better way to give the dialog a proper size (desktop view / mobile view) without using css workarounds.
Adapt the information message as you consider more adequate.

**Comment by DavidePrincipi** [comment]
Hi @dnutan what do you think to avoid the dialog box style and open a new screen?

image

I'd avoid a generic reference to NethServer or Samba docs. I prefer a simple sentence:

    [!] Changing the Domain Controller IP address can cause problems
    to Active Directory clients. If they use an external DNS server, 
    update it to use the new IP address.

I hope it is clear enough: what do you think?

**Comment by dnutan** [comment]
It's fine, and the message clearest.
Accepted.

**Comment by DavidePrincipi** [comment]
I cannot push the last commit to your fork master branch. As the patch affects two files I cannot use the web interface, too. 

So I merged your PR as-is and will add my commit later. Thank you very much for this PR!

**Pull request merged**
