### PR TITLE
Admin script to delete users

### PR DESCRIPTION
**Pull request by stephdl**
https://github.com/NethServer/dev/issues/5657

### CODE REVIEW

**Comment by gsanchietti** [comment]
I agree with Davide: I was asking myself what was the purpose of the remove-all script :)

**Comment by stephdl** [comment]
each year a sysadmin in school could need  to remove all users and start again with a new bunch of users.
the student has changed of courses
the teacher is no more working in this school

As ever I did it because I could do it :D

**Comment by gsanchietti** [comment]
After reading community threads (and after some experiences from customer) It seems that "delete all" is not real usage scenario. Maybe the admin will need to change most of users, but for sure not all of them.

Adding code, means support it for future releases: I'd like to remove the "remove-all" script.
Also bear in mind that "remove-all" is a special case of "remove-some" script.

**Comment by stephdl** [comment]
@gsanchietti @DavidePrincipi  delete_all_users has been removed, documentation modified, could I merge ?

**Pull request merged**
